name: Release the lib

on:
  push:
    tags:
    - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install latest stable Rust
      uses: dtolnay/rust-toolchain@stable

    - uses: Swatinem/rust-cache@v2

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1.0.5

    - name: Install Cargo targets
      run: rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android
      
    - name: Publish Release to Github
      uses: gradle/gradle-build-action@v2
      with:
        arguments: publishReleasePublicationToGithubPackagesRepository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Publish Debug to Github
      uses: gradle/gradle-build-action@v2
      with:
        arguments: publishDebugPublicationToGithubPackagesRepository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Debug
      uses: actions/upload-artifact@v3
      with:
        name: debug-lib
        path: ./lib/build/outputs/aar/lib-debug.aar
